security:

  # For in-memory users used during setup/testing
  password_hashers:
    App\Entity\User:
      algorithm: auto


  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        csrf_token_id: authenticate
        username_parameter: email
        password_parameter: password
        default_target_path: app_user_dashboard
      logout:
        path: app_logout
        target: app_home

  role_hierarchy:
    ROLE_MANAGER: [ROLE_USER]
    ROLE_ADMIN: [ROLE_MANAGER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: ROLE_USER }
