parameters:
    fedapay_public_key: '%env(FEDAPAY_PUBLIC_KEY)%'
    # 📁 Dossier sécurisé hors de public
    upload_directory: '%kernel.project_dir%/var/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        # 🔹 Bind global pour tous les services
        bind:
            $projectDir: '%kernel.project_dir%'
            $uploadDir: '%upload_directory%'

    # Tous les services dans src/
    App\:
        resource: '../src/'

    # Services spécifiques
    App\Service\PdfGeneratorService: ~
    App\Service\MailerService: ~
    App\Service\FileUploader: ~
    App\Service\MembershipCardService: ~
    App\Service\PhotoUploadService: ~
    App\Service\ConfigurationService: ~
    App\Service\EmailService: ~
    App\Service\CardPaymentService: ~
    App\Service\QrCodeService:
        arguments:
            $privateStorageDir: '%kernel.project_dir%/var/uploads'

    # Commandes
    App\Command\TestEmailCardCommand: ~
    App\Command\FixEmailCardCommand: ~
    App\Command\TestFullRegistrationCommand: ~
    App\Command\TestPdfStylesCommand: ~
    App\Command\TestEmailToRodrigueCommand: ~
    App\Command\TestFedaPayIntegrationCommand: ~
    App\Command\TestFedaPayConfigCommand: ~
    App\Command\TestPaymentPdfCommand: ~
    App\Command\TestPdfDirectCommand: ~
    App\Command\TestBasicPdfCommand: ~
    App\Command\SetupUploadDirsCommand: ~
    App\Command\CheckPdfPathsCommand: ~
    App\Command\TestPaymentRedirectCommand: ~
    App\Command\TestPaymentRedirectFixCommand: ~
    App\Command\TestFedaPayRedirectFixCommand: ~
